# Generated by Django 5.1.2 on 2026-03-02 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('JieStoreApp', '0002_usercart_usercartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='itemImages/'),
        ),
    ]
